import type {
  Room, AdminUser, SyncLog, AppSettings, CalendarEvent, Booking, Campaign,
  Property, CustomerBooking, Review, CustomerProfile, CustomerNotification,
} from '../types';

// ─── Admin Mock Data ──────────────────────────────────────────────────────────

export const rooms: Room[] = [
  {
    roomId: 1,
    title: 'Aqua Retreat',
    category: 'villa',
    type: 'Villa',
    description: 'Set across nearly 2 acres of serene landscape, this exclusive 3-bedroom luxury villa offers a private swimming pool, expansive landscaped gardens, and breathtaking lake views.',
    price: 25000,
    capacity: 6,
    totalRooms: 1,
    sizeSqFt: 3500,
    amenities: ['Wifi', 'Air Conditioning', 'Private swimming pool', 'Expansive landscaped gardens', 'Lake views'],
    featured: true,
    status: 'active',
    images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=600&q=80'],
    airbnbIcalUrl: 'https://www.airbnb.com/calendar/ical/1',
    airbnbCalendarUrl: 'https://www.airbnb.com/rooms/1',
    syncEnabled: true,
    syncStatus: 'ok',
    lastSyncedAt: new Date(Date.now() - 3600000).toISOString(),
    hostId: 'host_demo',
    approvedByAdmin: true,
    bedrooms: 3,
    hasSwimmingPool: true,
    hasLawn: true,
    hasOnPropertyStaff: true,
    cleanlinessScore: 5,
  },
  {
    roomId: 2,
    title: 'Villanova',
    category: 'villa',
    type: 'Villa',
    description: 'Experience refined luxury in this stunning 5-bedroom villa featuring elegant architecture, private pool, and lush greenery.',
    price: 35000,
    capacity: 10,
    totalRooms: 1,
    sizeSqFt: 5000,
    amenities: ['Wifi', 'Air Conditioning', 'Private swimming pool', 'Gym', 'Lounge Area'],
    featured: true,
    status: 'active',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80'],
    airbnbIcalUrl: '',
    airbnbCalendarUrl: '',
    syncEnabled: false,
    hostId: 'host_demo',
    approvedByAdmin: true,
    bedrooms: 5,
    hasSwimmingPool: true,
    hasLawn: true,
    hasOnPropertyStaff: true,
    cleanlinessScore: 5,
  },
  {
    roomId: 3,
    title: 'Seaside Farmhouse',
    category: 'farmhouse',
    type: 'Farmhouse',
    description: 'A beachfront escape with scenic views. Cozy and rustic.',
    price: 18000,
    capacity: 8,
    totalRooms: 1,
    sizeSqFt: 2200,
    amenities: ['Wifi', 'Lawn', 'Beach Access'],
    featured: false,
    status: 'hidden',
    images: ['https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=600&q=80'],
    hostId: 'usr_3',
    approvedByAdmin: false,
    bedrooms: 2,
    hasSwimmingPool: false,
    hasLawn: true,
    hasOnPropertyStaff: true,
    cleanlinessScore: 4,
  },
  {
    roomId: 4,
    title: 'Green Valley Retreat',
    category: 'farmhouse',
    type: 'Farmhouse',
    description: 'Lush green farmhouse with an infinity pool, 3 bedrooms, and dedicated security/caretaker.',
    price: 15000,
    capacity: 6,
    totalRooms: 1,
    sizeSqFt: 3000,
    amenities: ['Wifi', 'Swimming Pool', 'Lawn', 'Bonfire'],
    featured: false,
    status: 'hidden',
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80'],
    hostId: 'usr_3',
    approvedByAdmin: false,
    bedrooms: 3,
    hasSwimmingPool: true,
    hasLawn: true,
    hasOnPropertyStaff: true,
    cleanlinessScore: 5,
  },
];

export const users: AdminUser[] = [
  {
    id: 'usr_1',
    name: 'Kalesha Baig',
    email: 'kalesha@larosa.com',
    role: 'admin',
    createdAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'usr_2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    role: 'customer',
    createdAt: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'usr_3',
    name: 'John Host',
    email: 'john@host.com',
    role: 'host',
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    hostVerificationStatus: 'pending',
    govtId: {
      type: 'Aadhaar Card',
      number: '4820-1928-3746',
      documentUrl: 'aadhar_proof.png'
    },
    bankDetails: {
      accountHolderName: 'John Host',
      bankAccountNumber: '9182736450192',
      ifscCode: 'HDFC0001827',
      upiId: 'john@okhdfc'
    },
    propertyProof: {
      ownershipProofUrl: 'deed_of_sale.pdf',
      addressProofUrl: 'electricity_bill.pdf'
    }
  },
  {
    id: 'host_demo',
    name: 'Priya Sharma',
    email: 'host@larosa.in',
    role: 'host',
    createdAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
    phone: '+91 98765 11111',
    hostVerificationStatus: 'verified',
  },
];

export const syncLogs: SyncLog[] = [
  {
    id: 'log_1',
    roomId: 1,
    success: true,
    startedAt: new Date(Date.now() - 3650000).toISOString(),
    finishedAt: new Date(Date.now() - 3600000).toISOString(),
    eventsImported: 4,
    eventsRemoved: 1,
  },
  {
    id: 'log_2',
    roomId: 2,
    success: false,
    startedAt: new Date(Date.now() - 7200000).toISOString(),
    finishedAt: new Date(Date.now() - 7180000).toISOString(),
    errorMessage: 'Failed to fetch Airbnb ICS feed. Network timeout.',
  },
];

export const settings: AppSettings = {
  property: {
    propertyName: 'Larosa Luxury Villas',
    address: 'Lakefront Estate, Kerala, India',
    timezone: 'Asia/Kolkata',
    checkInTime: '14:00',
    checkOutTime: '11:00',
    supportEmail: 'support@larosavillas.com',
    supportPhone: '+91 98765 43210',
  },
  billing: {
    currency: 'INR',
    razorpayKeyId: 'rzp_live_kalesha123',
    webhookUrl: 'https://api.larosavillas.com/webhooks/razorpay',
    webhookSecretSet: true,
  },
  security: {
    requireAdmin2fa: true,
    sessionTimeoutMinutes: 60,
  },
  notifications: {
    msg91AuthKeySet: true,
    msg91FlowId: 'flow_larosa_booking',
    adminAlertPhones: ['+919876543210'],
    emailAlertsEnabled: true,
    smsAlertsEnabled: true,
  },
  channel: {
    statusMessage: 'Villas are synced with Airbnb calendar feeds.',
    syncEnabled: true,
  },
};

export const calendarEvents: CalendarEvent[] = [
  {
    id: 'evt_1',
    roomId: 1,
    start: '2026-08-05',
    end: '2026-08-10',
    title: 'John Doe Booking',
    source: 'website',
    blocked: false,
    bookingId: 'bk_1',
  },
  {
    id: 'evt_2',
    roomId: 1,
    start: '2026-08-15',
    end: '2026-08-18',
    title: 'Airbnb Sync Reservation',
    source: 'airbnb',
    blocked: false,
    bookingId: 'bk_2',
  },
  {
    id: 'evt_3',
    roomId: 1,
    start: '2026-08-22',
    end: '2026-08-25',
    title: 'Owner Blockout',
    source: 'manual',
    blocked: true,
  },
];

export const bookings: Booking[] = [
  {
    id: 'bk_1',
    roomId: 1,
    roomTitle: 'Aqua Retreat',
    roomType: 'Villa',
    guestName: 'John Doe',
    guestEmail: 'john@doe.com',
    guestPhone: '+91 99999 88888',
    specialRequests: 'Need high chair and pool toys.',
    checkIn: '2026-08-05',
    checkOut: '2026-08-10',
    nights: 5,
    guests: 4,
    pricePerNight: 25000,
    totalPrice: 125000,
    razorpayOrderId: 'order_john123',
    razorpayPaymentId: 'pay_john123',
    source: 'website',
    status: 'confirmed',
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'bk_2',
    roomId: 1,
    roomTitle: 'Aqua Retreat',
    roomType: 'Villa',
    guestName: 'Airbnb Guest',
    guestEmail: 'guest-airbnb@airbnb.com',
    guestPhone: '+1 555 123 4567',
    checkIn: '2026-08-15',
    checkOut: '2026-08-18',
    nights: 3,
    guests: 2,
    pricePerNight: 25000,
    totalPrice: 75000,
    source: 'airbnb',
    status: 'pending',
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
];

export const dashboardStats = {
  totalRevenue: 200000,
  occupancyRate: 72,
  confirmed: 4,
  pending: 2,
  cancelled: 1,
};

export const revenueByMonth = [
  { month: '2026-02', total: 120000, label: 'Feb' },
  { month: '2026-03', total: 150000, label: 'Mar' },
  { month: '2026-04', total: 180000, label: 'Apr' },
  { month: '2026-05', total: 220000, label: 'May' },
  { month: '2026-06', total: 210000, label: 'Jun' },
  { month: '2026-07', total: 250000, label: 'Jul' },
];

export const currentAdmin = {
  name: 'Kalesha Baig',
  email: 'kalesha@larosa.in',
};

export interface AppNotification {
  id: string;
  title: string;
  message: string;
  read: boolean;
  createdAt: string;
}

export const notifications: AppNotification[] = [
  {
    id: 'not_1',
    title: 'New Booking Request',
    message: 'John Doe requested a booking for Aqua Retreat.',
    read: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'not_2',
    title: 'Sync Status Warning',
    message: 'Airbnb calendar sync failed for Villanova.',
    read: true,
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
];

export const campaigns: Campaign[] = [
  {
    campaignId: 'c1',
    name: 'Monsoon Offer',
    type: 'showcase',
    status: 'active',
    headline: 'Flat 20% off on Monsoons',
    message: 'Book any villa for 3 nights or more and get a complimentary wine bottle and dinner package.',
    ctaLabel: 'Book now',
    ctaUrl: '/villas',
    accent: 'gold',
    priority: 2,
    dismissible: true,
    imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80',
  },
  {
    campaignId: 'c2',
    name: 'Independence Day',
    type: 'strip',
    status: 'draft',
    headline: 'Celebrate Independence Day Weekend',
    message: 'Special rates starting from ₹15,000/night.',
    ctaLabel: 'View Rates',
    ctaUrl: '/villas',
    accent: 'navy',
    priority: 1,
    dismissible: false,
  },
];

// ─── Customer Mock Data ───────────────────────────────────────────────────────

export const properties: Property[] = [
  {
    id: 'prop_1',
    title: 'Aqua Retreat',
    location: 'Kumarakom, Kerala',
    city: 'Kumarakom',
    state: 'Kerala',
    description: 'Set across nearly 2 acres of serene landscape, this exclusive 3-bedroom luxury villa offers a private swimming pool, expansive landscaped gardens, and breathtaking lake views. Perfect for families and couples seeking a luxurious escape from city life. The villa features handcrafted teak furniture, curated artwork, and floor-to-ceiling windows that frame the lush greenery.',
    shortDescription: 'Lakefront luxury villa with private pool & stunning views',
    pricePerNight: 25000,
    weekendPricePerNight: 30000,
    deposit: 50000,
    platformFeePercent: 10,
    rating: 4.9,
    reviewCount: 87,
    capacity: 6,
    bedrooms: 3,
    bathrooms: 3,
    sizeSqFt: 3500,
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['WiFi', 'Air Conditioning', 'Private Pool', 'Landscaped Gardens', 'Lake Views', 'Smart TV', 'Kitchen', 'Free Parking', 'BBQ Area', 'Outdoor Shower'],
    houseRules: ['No smoking indoors', 'No pets allowed', 'No parties or events without prior approval', 'Quiet hours: 10 PM – 8 AM', 'Check-in: 2:00 PM', 'Check-out: 11:00 AM'],
    bookingType: 'instant',
    featured: true,
    category: 'villa',
    caretakerName: 'Rajan Nair',
    caretakerPhone: '+91 94456 78901',
    securityDeposit: 10000,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    minNights: 2,
    maxNights: 14,
    purposes: ['Family Vacation', 'Honeymoon', 'Corporate Retreat', 'Birthday Celebration', 'Anniversary'],
    lat: 9.6131,
    lng: 76.4320,
  },
  {
    id: 'prop_2',
    title: 'Villanova Estate',
    location: 'Coorg, Karnataka',
    city: 'Coorg',
    state: 'Karnataka',
    description: 'Experience refined luxury in this stunning 5-bedroom estate featuring elegant architecture, private pool, and lush coffee plantation views. Nestled in the misty hills of Coorg, Villanova offers an unparalleled retreat with personalized butler service, a farm-to-table dining experience, and curated nature walks through ancient coffee estates.',
    shortDescription: '5-bedroom hilltop estate amid Coorg coffee estates',
    pricePerNight: 35000,
    weekendPricePerNight: 42000,
    deposit: 75000,
    platformFeePercent: 10,
    rating: 4.8,
    reviewCount: 62,
    capacity: 10,
    bedrooms: 5,
    bathrooms: 5,
    sizeSqFt: 5000,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['WiFi', 'Air Conditioning', 'Private Pool', 'Gym', 'Lounge Area', 'Butler Service', 'Coffee Estate Tour', 'Fireplace', 'Home Theatre', 'Chef on Demand'],
    houseRules: ['No smoking indoors', 'No parties without approval', 'Pet-friendly (dogs only)', 'Quiet hours: 11 PM – 7 AM', 'Check-in: 2:00 PM', 'Check-out: 11:00 AM'],
    bookingType: 'request',
    featured: true,
    category: 'villa',
    caretakerName: 'Suresh Gowda',
    caretakerPhone: '+91 98765 43210',
    securityDeposit: 15000,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    minNights: 2,
    maxNights: 21,
    purposes: ['Family Reunion', 'Corporate Retreat', 'Wedding', 'Anniversary', 'Birthday'],
  },
  {
    id: 'prop_3',
    title: 'Monsoon Farmhouse',
    location: 'Alibaug, Maharashtra',
    city: 'Alibaug',
    state: 'Maharashtra',
    description: 'A charming 4-bedroom farmhouse with sweeping views of the Arabian Sea, tropical gardens, and a breathtaking infinity pool. Just 90 minutes from Mumbai, Monsoon Farmhouse is your perfect weekend escape — rustic luxury meets coastal serenity, with locally sourced seafood dinners arranged on request.',
    shortDescription: 'Coastal farmhouse with infinity pool & sea views',
    pricePerNight: 18000,
    weekendPricePerNight: 22000,
    deposit: 36000,
    platformFeePercent: 10,
    rating: 4.7,
    reviewCount: 134,
    capacity: 8,
    bedrooms: 4,
    bathrooms: 3,
    sizeSqFt: 3200,
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1596436889106-be35e843f974?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1609766857473-8bd374db54b5?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['WiFi', 'Infinity Pool', 'Sea Views', 'Tropical Gardens', 'Outdoor Dining', 'Bonfire Pit', 'Beach Access', 'Kayaks', 'Smart TV', 'Kitchen'],
    houseRules: ['No smoking', 'No pets', 'Children welcome', 'No loud music after 10 PM', 'Check-in: 1:00 PM', 'Check-out: 11:00 AM'],
    bookingType: 'instant',
    featured: true,
    category: 'farmhouse',
    caretakerName: 'Priya Patil',
    caretakerPhone: '+91 91234 56789',
    securityDeposit: 8000,
    checkInTime: '13:00',
    checkOutTime: '11:00',
    minNights: 1,
    maxNights: 10,
    purposes: ['Weekend Getaway', 'Family Vacation', 'Honeymoon', 'Friends Trip'],
  },
  {
    id: 'prop_4',
    title: 'Forest Hideaway',
    location: 'Wayanad, Kerala',
    city: 'Wayanad',
    state: 'Kerala',
    description: 'Tucked deep in the Western Ghats, Forest Hideaway is a 2-bedroom luxury treehouse-style cottage surrounded by dense forest, exotic wildlife, and a pristine stream. Solar-powered, with outdoor bathing, and surrounded by complete tranquility — this is a digital detox paradise.',
    shortDescription: 'Luxury treehouse cottage in the Western Ghats wilderness',
    pricePerNight: 14000,
    weekendPricePerNight: 17000,
    deposit: 28000,
    platformFeePercent: 10,
    rating: 4.9,
    reviewCount: 211,
    capacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqFt: 1800,
    images: [
      'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1615729947596-a598e5de0ab3?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['Nature Trails', 'Stream Access', 'Campfire', 'Organic Farm', 'Birdwatching', 'Outdoor Bath', 'Solar Power', 'Hammocks', 'Forest Views', 'Meditation Deck'],
    houseRules: ['No noise that disturbs wildlife', 'No plastic bottles', 'Check-in: 3:00 PM', 'Check-out: 10:00 AM', 'No campfires after midnight', 'Respect wildlife corridors'],
    bookingType: 'request',
    featured: false,
    category: 'cottage',
    caretakerName: 'Thomas Kuruvilla',
    caretakerPhone: '+91 97654 32109',
    securityDeposit: 5000,
    checkInTime: '15:00',
    checkOutTime: '10:00',
    minNights: 2,
    purposes: ['Honeymoon', 'Digital Detox', 'Nature Retreat', 'Photography'],
  },
  {
    id: 'prop_5',
    title: 'Sunset Manor',
    location: 'Lonavala, Maharashtra',
    city: 'Lonavala',
    state: 'Maharashtra',
    description: 'Perched on the edge of the Sahyadri hills, Sunset Manor offers spectacular valley views, a heated infinity pool, and 4 palatial suites across 2 floors. A short drive from Pune and Mumbai, it\'s the perfect blend of heritage architecture and modern luxury. Ideal for large family gatherings and corporate events.',
    shortDescription: 'Heritage hilltop manor with valley views & heated pool',
    pricePerNight: 28000,
    weekendPricePerNight: 34000,
    deposit: 60000,
    platformFeePercent: 10,
    rating: 4.6,
    reviewCount: 48,
    capacity: 12,
    bedrooms: 4,
    bathrooms: 4,
    sizeSqFt: 4500,
    images: [
      'https://images.unsplash.com/photo-1574739782594-db4ead022697?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1561501900-3701fa6a0864?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['WiFi', 'Heated Infinity Pool', 'Valley Views', 'Carom & Board Games', 'BBQ Area', 'Projector Room', 'Air Conditioning', 'Chef on Demand', 'DJ Setup', 'Bonfire Pit'],
    houseRules: ['No smoking indoors', 'No outside alcohol', 'Music allowed till 11 PM', 'No pets', 'Check-in: 2:00 PM', 'Check-out: 11:00 AM'],
    bookingType: 'instant',
    featured: true,
    category: 'villa',
    caretakerName: 'Vijay Shinde',
    caretakerPhone: '+91 96543 21098',
    securityDeposit: 12000,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    minNights: 2,
    purposes: ['Corporate Retreat', 'Family Reunion', 'Birthday Party', 'Team Building', 'Wedding'],
  },
  {
    id: 'prop_6',
    title: 'Riverside Bungalow',
    location: 'Coorg, Karnataka',
    city: 'Coorg',
    state: 'Karnataka',
    description: 'A serene 3-bedroom bungalow on the banks of the Cauvery river, surrounded by coffee estates and spice gardens. Wake up to the sound of the river, enjoy kayaking, and savor authentic Coorgi cuisine prepared by the resident cook. A rejuvenating experience for nature lovers.',
    shortDescription: '3-bedroom riverside bungalow on Cauvery riverbank',
    pricePerNight: 16000,
    weekendPricePerNight: 20000,
    deposit: 32000,
    platformFeePercent: 10,
    rating: 4.7,
    reviewCount: 93,
    capacity: 6,
    bedrooms: 3,
    bathrooms: 2,
    sizeSqFt: 2800,
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1553653924-39b70295f8da?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['River Frontage', 'Kayaking', 'Coffee Estate Walk', 'Spice Garden', 'Resident Cook', 'Bonfire', 'WiFi', 'Air Conditioning', 'Outdoor Dining', 'Bird Watching'],
    houseRules: ['No swimming in the river', 'Campfire with supervision only', 'No plastic', 'Check-in: 1:00 PM', 'Check-out: 11:00 AM', 'Pets allowed (on prior request)'],
    bookingType: 'instant',
    featured: false,
    category: 'farmhouse',
    caretakerName: 'Manju Cariappa',
    caretakerPhone: '+91 99001 23456',
    securityDeposit: 8000,
    checkInTime: '13:00',
    checkOutTime: '11:00',
    minNights: 2,
    purposes: ['Family Vacation', 'Honeymoon', 'Nature Retreat', 'Photography'],
  },
];

// ─── Customer Bookings ────────────────────────────────────────────────────────

export const customerBookings: CustomerBooking[] = [
  {
    id: 'cbk_1',
    propertyId: 'prop_1',
    propertyTitle: 'Aqua Retreat',
    propertyImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
    propertyLocation: 'Kumarakom, Kerala',
    checkIn: '2026-08-15',
    checkOut: '2026-08-19',
    nights: 4,
    guests: 4,
    bedrooms: 3,
    purpose: 'Family Vacation',
    pricePerNight: 25000,
    subtotal: 100000,
    deposit: 50000,
    platformFee: 10000,
    taxes: 2700,
    totalPrice: 112700,
    paidAmount: 62700,
    remainingAmount: 50000,
    paymentMethod: 'UPI',
    status: 'upcoming',
    paymentStatus: 'partial',
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    specialRequests: 'We need a high chair for a toddler.',
    bookingTimeline: [
      {
        id: 'tl_1',
        title: 'Booking Created',
        description: 'Your booking request was received and is being processed.',
        timestamp: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
        type: 'created',
      },
      {
        id: 'tl_2',
        title: 'Booking Confirmed',
        description: 'Your booking has been confirmed by the property host.',
        timestamp: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
        type: 'confirmed',
      },
      {
        id: 'tl_3',
        title: 'Deposit Paid',
        description: 'Deposit of ₹50,000 received via UPI.',
        timestamp: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
        type: 'paid',
      },
    ],
  },
  {
    id: 'cbk_2',
    propertyId: 'prop_2',
    propertyTitle: 'Villanova Estate',
    propertyImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    propertyLocation: 'Coorg, Karnataka',
    checkIn: '2026-09-05',
    checkOut: '2026-09-08',
    nights: 3,
    guests: 8,
    bedrooms: 5,
    purpose: 'Birthday Celebration',
    pricePerNight: 35000,
    subtotal: 105000,
    deposit: 75000,
    platformFee: 10500,
    taxes: 2835,
    totalPrice: 118335,
    paidAmount: 87835,
    remainingAmount: 30500,
    paymentMethod: 'Credit Card',
    status: 'upcoming',
    paymentStatus: 'partial',
    createdAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    bookingTimeline: [
      {
        id: 'tl_4',
        title: 'Booking Requested',
        description: 'Your booking request was sent to the host.',
        timestamp: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
        type: 'created',
      },
      {
        id: 'tl_5',
        title: 'Host Confirmed',
        description: 'Villanova Estate confirmed your booking.',
        timestamp: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
        type: 'confirmed',
      },
      {
        id: 'tl_6',
        title: 'Advance Paid',
        description: 'Advance of ₹87,835 paid via Credit Card.',
        timestamp: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
        type: 'paid',
      },
    ],
  },
  {
    id: 'cbk_3',
    propertyId: 'prop_3',
    propertyTitle: 'Monsoon Farmhouse',
    propertyImage: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=80',
    propertyLocation: 'Alibaug, Maharashtra',
    checkIn: '2026-06-10',
    checkOut: '2026-06-13',
    nights: 3,
    guests: 6,
    bedrooms: 4,
    purpose: 'Weekend Getaway',
    pricePerNight: 18000,
    subtotal: 54000,
    deposit: 36000,
    platformFee: 5400,
    taxes: 1458,
    totalPrice: 60858,
    paidAmount: 60858,
    remainingAmount: 0,
    paymentMethod: 'UPI',
    status: 'completed',
    paymentStatus: 'paid',
    createdAt: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(),
    bookingTimeline: [
      {
        id: 'tl_7',
        title: 'Booking Created',
        description: 'Booking confirmed instantly.',
        timestamp: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(),
        type: 'created',
      },
      {
        id: 'tl_8',
        title: 'Full Payment Done',
        description: 'Total amount ₹60,858 paid via UPI.',
        timestamp: new Date(Date.now() - 44 * 24 * 3600 * 1000).toISOString(),
        type: 'paid',
      },
      {
        id: 'tl_9',
        title: 'Checked In',
        description: 'Guests checked in at Monsoon Farmhouse.',
        timestamp: new Date(Date.now() - 37 * 24 * 3600 * 1000).toISOString(),
        type: 'checkin',
      },
      {
        id: 'tl_10',
        title: 'Checked Out',
        description: 'Stay completed. We hope you had a wonderful time!',
        timestamp: new Date(Date.now() - 34 * 24 * 3600 * 1000).toISOString(),
        type: 'checkout',
      },
    ],
  },
  {
    id: 'cbk_4',
    propertyId: 'prop_5',
    propertyTitle: 'Sunset Manor',
    propertyImage: 'https://images.unsplash.com/photo-1574739782594-db4ead022697?auto=format&fit=crop&w=800&q=80',
    propertyLocation: 'Lonavala, Maharashtra',
    checkIn: '2026-05-22',
    checkOut: '2026-05-24',
    nights: 2,
    guests: 10,
    bedrooms: 4,
    purpose: 'Corporate Retreat',
    pricePerNight: 28000,
    subtotal: 56000,
    deposit: 60000,
    platformFee: 5600,
    taxes: 1512,
    totalPrice: 63112,
    paidAmount: 0,
    remainingAmount: 63112,
    paymentMethod: 'Net Banking',
    status: 'cancelled',
    paymentStatus: 'refunded',
    createdAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
    cancelledAt: new Date(Date.now() - 58 * 24 * 3600 * 1000).toISOString(),
    bookingTimeline: [
      {
        id: 'tl_11',
        title: 'Booking Created',
        description: 'Your booking was placed.',
        timestamp: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
        type: 'created',
      },
      {
        id: 'tl_12',
        title: 'Booking Cancelled',
        description: 'Booking cancelled by guest before check-in.',
        timestamp: new Date(Date.now() - 58 * 24 * 3600 * 1000).toISOString(),
        type: 'cancelled',
      },
      {
        id: 'tl_13',
        title: 'Refund Initiated',
        description: 'Full refund of ₹63,112 initiated to Net Banking account.',
        timestamp: new Date(Date.now() - 57 * 24 * 3600 * 1000).toISOString(),
        type: 'refunded',
      },
    ],
  },
  {
    id: 'cbk_5',
    propertyId: 'prop_4',
    propertyTitle: 'Forest Hideaway',
    propertyImage: 'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=800&q=80',
    propertyLocation: 'Wayanad, Kerala',
    checkIn: '2026-04-10',
    checkOut: '2026-04-13',
    nights: 3,
    guests: 2,
    bedrooms: 2,
    purpose: 'Honeymoon',
    pricePerNight: 14000,
    subtotal: 42000,
    deposit: 28000,
    platformFee: 4200,
    taxes: 1134,
    totalPrice: 47334,
    paidAmount: 47334,
    remainingAmount: 0,
    paymentMethod: 'Credit Card',
    status: 'completed',
    paymentStatus: 'paid',
    createdAt: new Date(Date.now() - 100 * 24 * 3600 * 1000).toISOString(),
    specialRequests: 'Honeymoon decoration please.',
    bookingTimeline: [
      {
        id: 'tl_14',
        title: 'Booking Confirmed',
        description: 'Booking confirmed by Forest Hideaway.',
        timestamp: new Date(Date.now() - 100 * 24 * 3600 * 1000).toISOString(),
        type: 'confirmed',
      },
      {
        id: 'tl_15',
        title: 'Full Payment Done',
        description: 'Amount ₹47,334 paid via Credit Card.',
        timestamp: new Date(Date.now() - 99 * 24 * 3600 * 1000).toISOString(),
        type: 'paid',
      },
      {
        id: 'tl_16',
        title: 'Checked In',
        description: 'Honeymoon setup ready. Enjoy your stay!',
        timestamp: new Date(Date.now() - 87 * 24 * 3600 * 1000).toISOString(),
        type: 'checkin',
      },
      {
        id: 'tl_17',
        title: 'Checked Out',
        description: 'We hope it was magical! Review your stay.',
        timestamp: new Date(Date.now() - 84 * 24 * 3600 * 1000).toISOString(),
        type: 'checkout',
      },
    ],
  },
];

// ─── Reviews ──────────────────────────────────────────────────────────────────

export const reviews: Review[] = [
  {
    id: 'rev_1',
    propertyId: 'prop_1',
    reviewerName: 'Priya Sharma',
    reviewerInitials: 'PS',
    rating: 5,
    title: 'Absolutely magical stay!',
    comment: 'We spent 4 nights at Aqua Retreat and it was everything we dreamed of. The lake views from the bedroom were breathtaking, the pool was pristine, and Rajan (caretaker) was incredibly hospitable. Will definitely return!',
    createdAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    helpful: 24,
    aspects: { cleanliness: 5, location: 5, value: 4, service: 5 },
    stayDuration: '4 nights',
    purpose: 'Family Vacation',
  },
  {
    id: 'rev_2',
    propertyId: 'prop_1',
    reviewerName: 'Rahul Mehta',
    reviewerInitials: 'RM',
    rating: 5,
    title: 'Perfect anniversary getaway',
    comment: 'Booked this for our anniversary and it exceeded all expectations. The property is even more beautiful in person. The sunset over the lake is unreal. Caretaker was super helpful and arranged a surprise dinner by the pool.',
    createdAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
    helpful: 18,
    aspects: { cleanliness: 5, location: 5, value: 5, service: 5 },
    stayDuration: '3 nights',
    purpose: 'Anniversary',
  },
  {
    id: 'rev_3',
    propertyId: 'prop_1',
    reviewerName: 'Anjali Nair',
    reviewerInitials: 'AN',
    rating: 4,
    title: 'Beautiful villa, minor WiFi issues',
    comment: 'The villa itself is stunning — great pool, amazing location. The WiFi was a bit slow during our stay which was a minor inconvenience for work calls. Everything else was perfect. The gardens are a dream.',
    createdAt: new Date(Date.now() - 90 * 24 * 3600 * 1000).toISOString(),
    helpful: 11,
    aspects: { cleanliness: 5, location: 5, value: 4, service: 4 },
    stayDuration: '5 nights',
    purpose: 'Family Vacation',
  },
  {
    id: 'rev_4',
    propertyId: 'prop_2',
    reviewerName: 'Vikram Singh',
    reviewerInitials: 'VS',
    rating: 5,
    title: 'Best corporate retreat ever!',
    comment: 'Brought my entire team of 10 for a 3-day corporate retreat. The estate handled everything perfectly — meals, activities, the works. The coffee estate tour was a highlight for everyone. Already planning a repeat visit.',
    createdAt: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
    helpful: 32,
    aspects: { cleanliness: 5, location: 5, value: 4, service: 5 },
    stayDuration: '3 nights',
    purpose: 'Corporate Retreat',
  },
  {
    id: 'rev_5',
    propertyId: 'prop_2',
    reviewerName: 'Deepa Krishnan',
    reviewerInitials: 'DK',
    rating: 5,
    title: 'Coorg at its finest',
    comment: 'Villanova Estate is the crown jewel of Coorg stays. The misty mornings, the smell of coffee, the absolute luxury of the estate — it\'s a dream. The butler service is impeccable. Highly recommend the fireplace suite.',
    createdAt: new Date(Date.now() - 50 * 24 * 3600 * 1000).toISOString(),
    helpful: 27,
    aspects: { cleanliness: 5, location: 5, value: 4, service: 5 },
    stayDuration: '4 nights',
    purpose: 'Anniversary',
  },
  {
    id: 'rev_6',
    propertyId: 'prop_3',
    reviewerName: 'Kiran Joshi',
    reviewerInitials: 'KJ',
    rating: 4,
    title: 'Quick Mumbai escape, great value',
    comment: 'Perfect for a quick weekend getaway from Mumbai. The sea views are stunning and the infinity pool is fabulous. The seafood dinner arranged by Priya was the highlight. Only wish it was a bit bigger.',
    createdAt: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
    helpful: 9,
    aspects: { cleanliness: 4, location: 5, value: 5, service: 4 },
    stayDuration: '2 nights',
    purpose: 'Weekend Getaway',
  },
  {
    id: 'rev_7',
    propertyId: 'prop_3',
    reviewerName: 'Sneha Patel',
    reviewerInitials: 'SP',
    rating: 5,
    title: 'Romantic and serene',
    comment: 'My husband and I stayed here for our first anniversary. The tropical gardens, the private pool at sunset, and the ocean breeze made it absolutely perfect. Priya (caretaker) was warm and welcoming.',
    createdAt: new Date(Date.now() - 40 * 24 * 3600 * 1000).toISOString(),
    helpful: 14,
    aspects: { cleanliness: 5, location: 5, value: 4, service: 5 },
    stayDuration: '3 nights',
    purpose: 'Honeymoon',
  },
  {
    id: 'rev_8',
    propertyId: 'prop_4',
    reviewerName: 'Aditya Kumar',
    reviewerInitials: 'AK',
    rating: 5,
    title: 'Life-changing forest experience',
    comment: 'I don\'t say this lightly — this was the most peaceful, beautiful stay of my life. No phone signal (mostly), birds waking you up at dawn, a stream right outside. The outdoor bath under the stars is an experience everyone must have.',
    createdAt: new Date(Date.now() - 25 * 24 * 3600 * 1000).toISOString(),
    helpful: 41,
    aspects: { cleanliness: 5, location: 5, value: 5, service: 5 },
    stayDuration: '4 nights',
    purpose: 'Digital Detox',
  },
  {
    id: 'rev_9',
    propertyId: 'prop_4',
    reviewerName: 'Meera Iyer',
    reviewerInitials: 'MI',
    rating: 5,
    title: 'Perfect honeymoon nest',
    comment: 'Thomas (caretaker) went above and beyond for our honeymoon. Rose petals, a custom dinner by the stream, stargazing from the deck — every detail was perfect. We\'ve already planned our anniversary trip back here.',
    createdAt: new Date(Date.now() - 70 * 24 * 3600 * 1000).toISOString(),
    helpful: 38,
    aspects: { cleanliness: 5, location: 5, value: 5, service: 5 },
    stayDuration: '5 nights',
    purpose: 'Honeymoon',
  },
  {
    id: 'rev_10',
    propertyId: 'prop_5',
    reviewerName: 'Rohit Gupta',
    reviewerInitials: 'RG',
    rating: 4,
    title: 'Great party venue',
    comment: 'Booked Sunset Manor for a birthday party of 12. The DJ setup was perfect, the infinity pool at sunset is incredible, and the valley views at night are stunning. Vijay (caretaker) was very accommodating. Will book again for our next event.',
    createdAt: new Date(Date.now() - 35 * 24 * 3600 * 1000).toISOString(),
    helpful: 16,
    aspects: { cleanliness: 4, location: 5, value: 4, service: 4 },
    stayDuration: '2 nights',
    purpose: 'Birthday Party',
  },
  {
    id: 'rev_11',
    propertyId: 'prop_6',
    reviewerName: 'Supriya Das',
    reviewerInitials: 'SD',
    rating: 5,
    title: 'A slice of paradise',
    comment: 'Waking up to the sound of the Cauvery river every morning was magical. The coffee estate walks, the organic meals, and Manju\'s warm hospitality made this one of our favorite stays ever. Highly recommended for anyone who loves nature.',
    createdAt: new Date(Date.now() - 18 * 24 * 3600 * 1000).toISOString(),
    helpful: 22,
    aspects: { cleanliness: 5, location: 5, value: 5, service: 5 },
    stayDuration: '4 nights',
    purpose: 'Family Vacation',
  },
];

// ─── Customer Profile ─────────────────────────────────────────────────────────

export const customerProfile: CustomerProfile = {
  id: 'cust_1',
  name: 'Arjun Mehta',
  email: 'arjun@example.com',
  phone: '+91 98765 12345',
  joinedAt: new Date(Date.now() - 180 * 24 * 3600 * 1000).toISOString(),
  isEmailVerified: true,
  isPhoneVerified: true,
  isIdentityVerified: false,
  totalBookings: 5,
  favoriteIds: ['prop_1', 'prop_4'],
};

// ─── Customer Notifications ───────────────────────────────────────────────────

export const customerNotifications: CustomerNotification[] = [
  {
    id: 'cn_1',
    title: 'Booking Confirmed! 🎉',
    message: 'Your booking at Aqua Retreat (Aug 15–19) has been confirmed. Prepare for an unforgettable stay!',
    type: 'booking',
    read: false,
    createdAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    bookingId: 'cbk_1',
  },
  {
    id: 'cn_2',
    title: 'Payment Reminder',
    message: 'Remaining balance of ₹50,000 for Aqua Retreat is due 2 days before check-in.',
    type: 'payment',
    read: false,
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    bookingId: 'cbk_1',
  },
  {
    id: 'cn_3',
    title: 'Check-in Reminder',
    message: 'You check in at Villanova Estate in 20 days. Start packing!',
    type: 'reminder',
    read: true,
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    bookingId: 'cbk_2',
  },
  {
    id: 'cn_4',
    title: 'Monsoon Special Offer 🌧️',
    message: 'Get 20% off on all farmhouse bookings this monsoon season. Limited slots available!',
    type: 'offer',
    read: true,
    createdAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'cn_5',
    title: 'Review Your Stay',
    message: 'How was your stay at Monsoon Farmhouse? Share your experience to help other guests.',
    type: 'system',
    read: true,
    createdAt: new Date(Date.now() - 34 * 24 * 3600 * 1000).toISOString(),
    bookingId: 'cbk_3',
  },
  {
    id: 'cn_6',
    title: 'Refund Processed',
    message: 'Your refund of ₹63,112 for Sunset Manor has been initiated. Expected in 3-5 business days.',
    type: 'payment',
    read: true,
    createdAt: new Date(Date.now() - 57 * 24 * 3600 * 1000).toISOString(),
    bookingId: 'cbk_4',
  },
];

export const supportTickets = [
  {
    id: 'tkt_1',
    user: 'Jane Smith',
    role: 'customer' as const,
    subject: 'Payment processing error',
    message: 'I tried to book Aqua Retreat but the Razorpay payment got stuck at processing, although money was deducted from my UPI account.',
    status: 'open' as const,
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    messages: [
      { sender: 'Jane Smith', text: 'I tried to book Aqua Retreat but the Razorpay payment got stuck at processing, although money was deducted from my UPI account.', time: '14:22' },
      { sender: 'System', text: 'Support request received. A representative will contact you shortly.', time: '14:23' }
    ]
  },
  {
    id: 'tkt_2',
    user: 'Villanova Host',
    role: 'host' as const,
    subject: 'Listing approval delay',
    message: 'Hi, I uploaded my farmhouse details yesterday but it is still pending approval. Can you please check if everything is OK?',
    status: 'open' as const,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    messages: [
      { sender: 'Villanova Host', text: 'Hi, I uploaded my farmhouse details yesterday but it is still pending approval. Can you please check if everything is OK?', time: '09:15' }
    ]
  }
];

export const reportedItems = [
  {
    id: 'rep_1',
    type: 'property' as const,
    targetId: 'prop_2',
    targetName: 'Villanova Estate',
    reason: 'Listing photos are misleading. The infinity pool was closed and there was construction noise.',
    reporterName: 'Jane Smith',
    status: 'pending' as const,
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString()
  },
  {
    id: 'rep_2',
    type: 'user' as const,
    targetId: 'usr_2',
    targetName: 'Jane Smith',
    reason: 'Guest threw a loud party violating the house rules and damaged property furniture.',
    reporterName: 'Coorg Host',
    status: 'pending' as const,
    createdAt: new Date(Date.now() - 3600000 * 72).toISOString()
  }
];

